version: '3.7'

networks:
  default:

services:
  fpm: &app-container
    build:
      context: ./local
      dockerfile: Dockerfile_fpm
    container_name: parse_fpm
    networks:
      - default
    volumes:
      - &data-app ../:/app
      - ./local/config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./local/config/fpm/php.ini:/usr/local/etc/php/php.ini
      - ./local/config/fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment: &fpm-env
      PHP_IDE_CONFIG: serverName=docker-parse
      REMOTE_HOST: host.docker.internal
      DB_HOST: postgres
      DB_DATABASE: &db-name app
      DB_USERNAME: &db-username root
      DB_PASSWORD: &db-password pass
      APP_ENV: local
      HOME: /app
      UID: 1000
      GID: 1000
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    restart: always
    container_name: parse_redis
    networks:
      - default

  queue-worker:
    <<: *app-container
    container_name: parse_queue
    command: "art queue:work"
    depends_on:
      - fpm

  nginx:
    build:
      context: ./local
      dockerfile: Dockerfile_nginx
    container_name: parse_nginx
    ports:
      - 28594:80
    restart: always
    volumes:
      - *data-app
      - ./local/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./local/config/nginx/site.conf:/etc/nginx/site.conf
    networks:
      - default
    depends_on:
      - fpm

  postgres:
      image: postgres:13.1-alpine
      networks:
          - default
      deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
      container_name: parse_db
      environment:
          POSTGRES_DB: *db-name
          POSTGRES_USER: *db-username
          POSTGRES_PASSWORD: *db-password
      ports:
          - 9440:5432
      volumes:
          - ./dbdata:/var/lib/postgresql/data

  rabbitmq:
      image: "rabbitmq:3-management"
      environment:
          RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
          RABBITMQ_DEFAULT_USER: "rabbitmq"
          RABBITMQ_DEFAULT_PASS: "rabbitmq"
          RABBITMQ_DEFAULT_VHOST: "/"
      ports:
          - 5672:5672
          - 15672:15672
      networks:
          - default
      container_name: parse_rabbitmq
